# Dependencies
markdown:         kramdown
kramdown:
  extensions: ["tables"]

highlighter:         true

# Permalinks
permalink:        pretty

# Setup
title:           Kang Landscaping
tagline:          'Los Angeles Glendale Hacienda Heights Landscaping Contractor Landscape Ka Kyoung'
url:              https://googleseo.herokuapp.com/
shorturl:         joshualande.com

author:
  name:           'Chung Sik Kang'
  url:            twitterURL

paginate:         1

# Custom vars
version:          1.0.0

github:
  repo:           mygithub

# This is the list of pages to include in the header of the website.
pages_list:       
  About: '/about/'
  Archive: '/archive/'
  Feed: '/atom.xml'

# Allow URL Redirects: 
#  * https://help.github.com/articles/redirects-on-github-pages
gems:
  - jekyll-redirect-from
  - jekyll-paginate
